INFO_SIZE = 7
BOARD_SIZE = 8
POLICY_OUT_CHANNEL = 80
PIECES_ORDER = 'KQRBNPkqrbnpE' # E: has ep

HISTORY_STATE_COUNTS = 8
INPUT_PIECE_STATES = HISTORY_STATE_COUNTS * (len(PIECES_ORDER) - 1) + 1
FULL_INPUT_STATES = INPUT_PIECE_STATES + INFO_SIZE
